/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package my.contacteditor;

/**
 *
 * @author Usuario
 */
public class MenuGerente extends javax.swing.JPanel {

    /**
     * Creates new form MenuGerente
     */
    public MenuGerente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IconSenha1 = new javax.swing.JLabel();
        IconTransferencia = new javax.swing.JLabel();
        IconRetiradasCaras = new javax.swing.JLabel();
        IconAplica = new javax.swing.JLabel();
        IconCliente = new javax.swing.JLabel();
        Banco1 = new javax.swing.JLabel();
        IconConta = new javax.swing.JLabel();
        ButtonLogout1 = new javax.swing.JButton();
        ButtonAlterarSenha1 = new javax.swing.JButton();
        ButtonRetiradasGrandes = new javax.swing.JButton();
        ButtonTransferencia = new javax.swing.JButton();
        ButtonAplicaSaldo = new javax.swing.JButton();
        ButtonVerificaConta = new javax.swing.JButton();
        ButtonVerificaCliente = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        TextSelecione1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu Gerência", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        IconSenha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/contacteditor/alterar_senha.png"))); // NOI18N

        IconTransferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transferencia.png"))); // NOI18N

        IconRetiradasCaras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/saco.png"))); // NOI18N

        IconAplica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dinheiro_add.png"))); // NOI18N

        IconCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cliente_dados.png"))); // NOI18N

        Banco1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        Banco1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/contacteditor/banco.png"))); // NOI18N
        Banco1.setText("Banco Paradigmas");

        IconConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/contas_dados.png"))); // NOI18N

        ButtonLogout1.setBackground(new java.awt.Color(255, 0, 51));
        ButtonLogout1.setText("Logout");
        ButtonLogout1.setName(""); // NOI18N

        ButtonAlterarSenha1.setText("Alterar senha");

        ButtonRetiradasGrandes.setText("Grandes retiradas");
        ButtonRetiradasGrandes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRetiradasGrandesActionPerformed(evt);
            }
        });

        ButtonTransferencia.setText("Transferência");

        ButtonAplicaSaldo.setText("Aplica saldo");
        ButtonAplicaSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAplicaSaldoActionPerformed(evt);
            }
        });

        ButtonVerificaConta.setText("Verificar contas");
        ButtonVerificaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVerificaContaActionPerformed(evt);
            }
        });

        ButtonVerificaCliente.setText("Verificar cliente");
        ButtonVerificaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVerificaClienteActionPerformed(evt);
            }
        });

        TextSelecione1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TextSelecione1.setText("Selecione uma Opção");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextSelecione1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ButtonVerificaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButtonVerificaConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButtonAplicaSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButtonTransferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButtonRetiradasGrandes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(IconRetiradasCaras)
                                                .addComponent(IconTransferencia, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(IconAplica, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(IconConta, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(IconCliente, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonAlterarSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IconSenha1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                        .addComponent(ButtonLogout1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Banco1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Banco1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextSelecione1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonVerificaCliente))
                    .addComponent(IconCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonVerificaConta)
                    .addComponent(IconConta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonAplicaSaldo)
                            .addComponent(IconAplica, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IconTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonTransferencia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonRetiradasGrandes))
                    .addComponent(IconRetiradasCaras, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonAlterarSenha1)
                    .addComponent(IconSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonLogout1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonVerificaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVerificaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonVerificaClienteActionPerformed

    private void ButtonVerificaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVerificaContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonVerificaContaActionPerformed

    private void ButtonAplicaSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAplicaSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAplicaSaldoActionPerformed

    private void ButtonRetiradasGrandesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRetiradasGrandesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonRetiradasGrandesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Banco1;
    private javax.swing.JButton ButtonAlterarSenha1;
    private javax.swing.JButton ButtonAplicaSaldo;
    private javax.swing.JButton ButtonLogout1;
    private javax.swing.JButton ButtonRetiradasGrandes;
    private javax.swing.JButton ButtonTransferencia;
    private javax.swing.JButton ButtonVerificaCliente;
    private javax.swing.JButton ButtonVerificaConta;
    private javax.swing.JLabel IconAplica;
    private javax.swing.JLabel IconCliente;
    private javax.swing.JLabel IconConta;
    private javax.swing.JLabel IconRetiradasCaras;
    private javax.swing.JLabel IconSenha1;
    private javax.swing.JLabel IconTransferencia;
    private javax.swing.JLabel TextSelecione1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
