/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class MenuClienteUI extends javax.swing.JPanel {

    /**
     * Creates new form MenuClienteUI
     */
    public MenuClienteUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextSelecione = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ButtonNovaConta = new javax.swing.JButton();
        ButtonAplicarDinheiro = new javax.swing.JButton();
        ButtonRetirarDinheiro = new javax.swing.JButton();
        ButtonVerificarSaldo = new javax.swing.JButton();
        ButtonVerificarExtrato = new javax.swing.JButton();
        ButtonAlterarSenha = new javax.swing.JButton();
        ButtonLogout = new javax.swing.JButton();
        Banco = new javax.swing.JLabel();
        IconNova = new javax.swing.JLabel();
        IconAplicar = new javax.swing.JLabel();
        IconRemover = new javax.swing.JLabel();
        IconSaldo = new javax.swing.JLabel();
        IconExtrato = new javax.swing.JLabel();
        IconSenha = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        TextSelecione.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TextSelecione.setText("Selecione uma Opção");

        ButtonNovaConta.setText("Abrir conta");
        ButtonNovaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNovaContaActionPerformed(evt);
            }
        });

        ButtonAplicarDinheiro.setText("Aplicar dinheiro");
        ButtonAplicarDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAplicarDinheiroActionPerformed(evt);
            }
        });

        ButtonRetirarDinheiro.setText("Retirar dinheiro");
        ButtonRetirarDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRetirarDinheiroActionPerformed(evt);
            }
        });

        ButtonVerificarSaldo.setText("Verificar saldo");

        ButtonVerificarExtrato.setText("Verificar extrato");

        ButtonAlterarSenha.setText("Alterar senha");

        ButtonLogout.setBackground(new java.awt.Color(255, 0, 51));
        ButtonLogout.setText("Logout");
        ButtonLogout.setName(""); // NOI18N

        Banco.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        Banco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/contacteditor/banco.png"))); // NOI18N
        Banco.setText("Banco Paradigmas");

        IconNova.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/contacteditor/conta_nova.png"))); // NOI18N

        IconAplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/contacteditor/dinheiro_add.png"))); // NOI18N

        IconRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/contacteditor/dinheiro_rem.png"))); // NOI18N

        IconSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/contacteditor/dinheiro.png"))); // NOI18N

        IconExtrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/contacteditor/extrato.png"))); // NOI18N

        IconSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/contacteditor/alterar_senha.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Banco))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ButtonNovaConta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonAplicarDinheiro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonRetirarDinheiro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonVerificarSaldo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonAlterarSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonVerificarExtrato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IconNova)
                                    .addComponent(IconAplicar)
                                    .addComponent(IconRemover)
                                    .addComponent(IconExtrato)
                                    .addComponent(IconSaldo))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IconSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                                .addComponent(ButtonLogout))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextSelecione)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Banco)
                .addGap(5, 5, 5)
                .addComponent(TextSelecione)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IconRemover, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonNovaConta)
                            .addComponent(IconNova, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonAplicarDinheiro)
                            .addComponent(IconAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonRetirarDinheiro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonVerificarSaldo)
                    .addComponent(IconSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonVerificarExtrato)
                    .addComponent(IconExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonAlterarSenha)
                        .addComponent(ButtonLogout))
                    .addComponent(IconSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAplicarDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAplicarDinheiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAplicarDinheiroActionPerformed

    private void ButtonRetirarDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRetirarDinheiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonRetirarDinheiroActionPerformed

    private void ButtonNovaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNovaContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonNovaContaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Banco;
    private javax.swing.JButton ButtonAlterarSenha;
    private javax.swing.JButton ButtonAplicarDinheiro;
    private javax.swing.JButton ButtonLogout;
    private javax.swing.JButton ButtonNovaConta;
    private javax.swing.JButton ButtonRetirarDinheiro;
    private javax.swing.JButton ButtonVerificarExtrato;
    private javax.swing.JButton ButtonVerificarSaldo;
    private javax.swing.JLabel IconAplicar;
    private javax.swing.JLabel IconExtrato;
    private javax.swing.JLabel IconNova;
    private javax.swing.JLabel IconRemover;
    private javax.swing.JLabel IconSaldo;
    private javax.swing.JLabel IconSenha;
    private javax.swing.JLabel TextSelecione;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
