/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.contacteditor;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class MenuGerencia extends javax.swing.JFrame{
    private static ArrayList<Gerente> ListaUsuarios;
    private static int indexGerente;
    private static Gerente GLogado;
    
    public MenuGerencia(ArrayList<Gerente> Lista, int index) {
        initComponents();
        ListaUsuarios = Lista;
        indexGerente = index;
        GLogado = Lista.get(index);     
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PMenu = new javax.swing.JPanel();
        IconLimite = new javax.swing.JLabel();
        IconTransferencia = new javax.swing.JLabel();
        IconRetiradasCaras = new javax.swing.JLabel();
        IconAplica = new javax.swing.JLabel();
        IconCliente = new javax.swing.JLabel();
        IconConta = new javax.swing.JLabel();
        IconCadastro = new javax.swing.JLabel();
        IconSenha = new javax.swing.JLabel();
        Banco = new javax.swing.JLabel();
        TextSelecione1 = new javax.swing.JLabel();
        ButtonLogout1 = new javax.swing.JButton();
        ButtonLimites = new javax.swing.JButton();
        ButtonRetiradasGrandes = new javax.swing.JButton();
        ButtonTransferencia = new javax.swing.JButton();
        ButtonAplicaSaldo = new javax.swing.JButton();
        ButtonVerificaConta = new javax.swing.JButton();
        ButtonVerificaCliente = new javax.swing.JButton();
        ButtonAlterarSenha = new javax.swing.JButton();
        ButtonCadastro = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        PVerificarCliente = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Banco1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        PVerificarConta = new javax.swing.JPanel();
        Banco2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField5 = new javax.swing.JTextField();
        PAplicarDinheiro = new javax.swing.JPanel();
        Banco3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jTextField4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        PTransferencias = new javax.swing.JPanel();
        Banco4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        PGrandesRetiradas = new javax.swing.JPanel();
        Banco5 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jTextField13 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        PEditar = new javax.swing.JPanel();
        Banco6 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jTextField16 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        PCadastrar = new javax.swing.JPanel();
        Banco7 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jTextField18 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel32 = new javax.swing.JLabel();
        PAlteraSenha = new javax.swing.JPanel();
        Banco8 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jButton10 = new javax.swing.JButton();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel35 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PMenu.setBackground(new java.awt.Color(255, 255, 255));
        PMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu Gerência", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        PMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PMenuMouseClicked(evt);
            }
        });
        PMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconLimite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/limites.png"))); // NOI18N
        PMenu.add(IconLimite, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, 23));

        IconTransferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transferencia.png"))); // NOI18N
        PMenu.add(IconTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, 23));

        IconRetiradasCaras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/saco.png"))); // NOI18N
        PMenu.add(IconRetiradasCaras, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, 23));

        IconAplica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dinheiro_add.png"))); // NOI18N
        PMenu.add(IconAplica, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, 23));

        IconCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cliente_dados.png"))); // NOI18N
        PMenu.add(IconCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, 23));

        IconConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/contas_dados.png"))); // NOI18N
        PMenu.add(IconConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, 23));

        IconCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tsicons.com-Add User Group Woman Man-16.png"))); // NOI18N
        PMenu.add(IconCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, 23));

        IconSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/alterar_senha.png"))); // NOI18N
        PMenu.add(IconSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, 23));

        Banco.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        Banco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/banco.png"))); // NOI18N
        Banco.setText("Banco Paradigmas");
        PMenu.add(Banco, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, -1, -1));

        TextSelecione1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TextSelecione1.setText("Selecione uma Opção");
        PMenu.add(TextSelecione1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 43, -1, -1));

        ButtonLogout1.setBackground(new java.awt.Color(255, 0, 51));
        ButtonLogout1.setText("Logout");
        ButtonLogout1.setName(""); // NOI18N
        ButtonLogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogout1ActionPerformed(evt);
            }
        });
        PMenu.add(ButtonLogout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, -1, -1));

        ButtonLimites.setText("Limites");
        ButtonLimites.setMaximumSize(new java.awt.Dimension(99, 23));
        ButtonLimites.setMinimumSize(new java.awt.Dimension(99, 23));
        ButtonLimites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLimitesActionPerformed(evt);
            }
        });
        PMenu.add(ButtonLimites, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 142, -1));

        ButtonRetiradasGrandes.setText("Grandes retiradas");
        ButtonRetiradasGrandes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRetiradasGrandesActionPerformed(evt);
            }
        });
        PMenu.add(ButtonRetiradasGrandes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 142, -1));

        ButtonTransferencia.setText("Transferência");
        ButtonTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTransferenciaActionPerformed(evt);
            }
        });
        PMenu.add(ButtonTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 142, -1));

        ButtonAplicaSaldo.setText("Aplicar saldo");
        ButtonAplicaSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAplicaSaldoActionPerformed(evt);
            }
        });
        PMenu.add(ButtonAplicaSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 142, -1));

        ButtonVerificaConta.setText("Verificar contas");
        ButtonVerificaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVerificaContaActionPerformed(evt);
            }
        });
        PMenu.add(ButtonVerificaConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 142, -1));

        ButtonVerificaCliente.setText("Verificar cliente");
        ButtonVerificaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVerificaClienteActionPerformed(evt);
            }
        });
        PMenu.add(ButtonVerificaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 142, -1));

        ButtonAlterarSenha.setText("Alterar senha");
        ButtonAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAlterarSenhaActionPerformed(evt);
            }
        });
        PMenu.add(ButtonAlterarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 142, -1));

        ButtonCadastro.setText("Cadastrar Usuário");
        ButtonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastroActionPerformed(evt);
            }
        });
        PMenu.add(ButtonCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 142, -1));
        PMenu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 830, 10));

        jTabbedPane1.addTab("Menu", PMenu);

        PVerificarCliente.setBackground(new java.awt.Color(255, 255, 255));
        PVerificarCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Verificar Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jButton1.setText("Procurar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Verificar o nome de seus clientes e quais são suas respectivas contas");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea1.setEnabled(false);
        jTextArea1.setMaximumSize(new java.awt.Dimension(200, 7000));
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("Nome:");

        jLabel3.setText("Contas:");

        Banco1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        Banco1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/banco.png"))); // NOI18N
        Banco1.setText("Banco Paradigmas");

        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PVerificarClienteLayout = new javax.swing.GroupLayout(PVerificarCliente);
        PVerificarCliente.setLayout(PVerificarClienteLayout);
        PVerificarClienteLayout.setHorizontalGroup(
            PVerificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PVerificarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PVerificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PVerificarClienteLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(PVerificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PVerificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PVerificarClienteLayout.createSequentialGroup()
                        .addGroup(PVerificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PVerificarClienteLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                                .addComponent(Banco1)))
                        .addContainerGap())))
        );
        PVerificarClienteLayout.setVerticalGroup(
            PVerificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PVerificarClienteLayout.createSequentialGroup()
                .addGroup(PVerificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PVerificarClienteLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1))
                    .addGroup(PVerificarClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Banco1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PVerificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PVerificarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("1", PVerificarCliente);

        PVerificarConta.setBackground(new java.awt.Color(255, 255, 255));
        PVerificarConta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Verificar Conta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        Banco2.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        Banco2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/banco.png"))); // NOI18N
        Banco2.setText("Banco Paradigmas");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Verificar as informações de cada uma das contas");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Número da conta:");

        jButton2.setText("Procurar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Nome do Cliente:");

        jTextField3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField3.setEnabled(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo da conta:");

        jLabel8.setText("Número da conta:");

        jTextField6.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField6.setEnabled(false);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField7.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField7.setEnabled(false);
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel9.setText("Saldo");

        jLabel10.setText("Extrato");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea2.setEnabled(false);
        jScrollPane2.setViewportView(jTextArea2);

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextField5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField5.setEnabled(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PVerificarContaLayout = new javax.swing.GroupLayout(PVerificarConta);
        PVerificarConta.setLayout(PVerificarContaLayout);
        PVerificarContaLayout.setHorizontalGroup(
            PVerificarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PVerificarContaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PVerificarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator5)
                    .addGroup(PVerificarContaLayout.createSequentialGroup()
                        .addGroup(PVerificarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PVerificarContaLayout.createSequentialGroup()
                                .addGroup(PVerificarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PVerificarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel6)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                        .addComponent(jTextField5))
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(PVerificarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10)
                                    .addGroup(PVerificarContaLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel8))
                                    .addGroup(PVerificarContaLayout.createSequentialGroup()
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2)))
                            .addComponent(jLabel4)
                            .addGroup(PVerificarContaLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))
                        .addGap(0, 311, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PVerificarContaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Banco2)
                .addGap(11, 11, 11))
        );
        PVerificarContaLayout.setVerticalGroup(
            PVerificarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PVerificarContaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Banco2)
                .addGap(1, 1, 1)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PVerificarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PVerificarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(1, 1, 1)
                .addGroup(PVerificarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PVerificarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(0, 0, 0)
                .addGroup(PVerificarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PVerificarContaLayout.createSequentialGroup()
                        .addComponent(jTextField5)
                        .addGap(202, 202, 202))
                    .addGroup(PVerificarContaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("2", PVerificarConta);

        PAplicarDinheiro.setBackground(new java.awt.Color(255, 255, 255));
        PAplicarDinheiro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aplicar Dinheiro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        Banco3.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        Banco3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/banco.png"))); // NOI18N
        Banco3.setText("Banco Paradigmas");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText(" Faz uma aplicação de dinheiro para um cliente específico");

        jLabel12.setText("Número da conta:");

        jLabel13.setText("Valor desejado:");

        jButton4.setText("Aplicar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel14.setText("Saldo da conta:");

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextField9.setEnabled(false);

        javax.swing.GroupLayout PAplicarDinheiroLayout = new javax.swing.GroupLayout(PAplicarDinheiro);
        PAplicarDinheiro.setLayout(PAplicarDinheiroLayout);
        PAplicarDinheiroLayout.setHorizontalGroup(
            PAplicarDinheiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAplicarDinheiroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator6)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PAplicarDinheiroLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, Short.MAX_VALUE)
                .addComponent(Banco3)
                .addGap(11, 11, 11))
            .addGroup(PAplicarDinheiroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator7)
                .addContainerGap())
            .addGroup(PAplicarDinheiroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PAplicarDinheiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PAplicarDinheiroLayout.createSequentialGroup()
                        .addGroup(PAplicarDinheiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PAplicarDinheiroLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(PAplicarDinheiroLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(17, 17, 17)))
                        .addGroup(PAplicarDinheiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField8)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addComponent(jButton4))
                    .addGroup(PAplicarDinheiroLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PAplicarDinheiroLayout.setVerticalGroup(
            PAplicarDinheiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAplicarDinheiroLayout.createSequentialGroup()
                .addGroup(PAplicarDinheiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PAplicarDinheiroLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Banco3)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PAplicarDinheiroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addGap(7, 7, 7)))
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PAplicarDinheiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(2, 2, 2)
                .addGroup(PAplicarDinheiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PAplicarDinheiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(225, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("3", PAplicarDinheiro);

        PTransferencias.setBackground(new java.awt.Color(255, 255, 255));
        PTransferencias.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transferências", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        Banco4.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        Banco4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/banco.png"))); // NOI18N
        Banco4.setText("Banco Paradigmas");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText(" Faz transferência de dinheiro entre contas específicas de clientes diferentes");

        jLabel16.setText("Número da conta de origem:");

        jButton5.setText("Transferir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel17.setText("Valor desejado:");

        jLabel18.setText("Número da conta destino:");

        javax.swing.GroupLayout PTransferenciasLayout = new javax.swing.GroupLayout(PTransferencias);
        PTransferencias.setLayout(PTransferenciasLayout);
        PTransferenciasLayout.setHorizontalGroup(
            PTransferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTransferenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PTransferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTransferenciasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Banco4))
                    .addComponent(jSeparator8)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PTransferenciasLayout.createSequentialGroup()
                        .addGroup(PTransferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5)
                            .addGroup(PTransferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PTransferenciasLayout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PTransferenciasLayout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PTransferenciasLayout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(PTransferenciasLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(375, Short.MAX_VALUE))
        );
        PTransferenciasLayout.setVerticalGroup(
            PTransferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTransferenciasLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Banco4)
                .addGap(2, 2, 2)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PTransferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PTransferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PTransferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("4", PTransferencias);

        PGrandesRetiradas.setBackground(new java.awt.Color(255, 255, 255));
        PGrandesRetiradas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Grandes Retiradas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        Banco5.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        Banco5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/banco.png"))); // NOI18N
        Banco5.setText("Banco Paradigmas");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Faz retiradas maiores de R$ 110.000,00 de contas de seus clientes");

        jLabel20.setText("Número da conta:");

        jLabel21.setText("Valor desejado:");

        jButton6.setText("Retirar");

        jLabel22.setText("Saldo da conta:");

        jTextField15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        javax.swing.GroupLayout PGrandesRetiradasLayout = new javax.swing.GroupLayout(PGrandesRetiradas);
        PGrandesRetiradas.setLayout(PGrandesRetiradasLayout);
        PGrandesRetiradasLayout.setHorizontalGroup(
            PGrandesRetiradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PGrandesRetiradasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator11)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PGrandesRetiradasLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Banco5)
                .addGap(11, 11, 11))
            .addGroup(PGrandesRetiradasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator12)
                .addContainerGap())
            .addGroup(PGrandesRetiradasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PGrandesRetiradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PGrandesRetiradasLayout.createSequentialGroup()
                        .addGroup(PGrandesRetiradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PGrandesRetiradasLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(PGrandesRetiradasLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(17, 17, 17)))
                        .addGroup(PGrandesRetiradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField14)
                            .addComponent(jTextField13, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addComponent(jButton6))
                    .addGroup(PGrandesRetiradasLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(545, Short.MAX_VALUE))
        );
        PGrandesRetiradasLayout.setVerticalGroup(
            PGrandesRetiradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PGrandesRetiradasLayout.createSequentialGroup()
                .addGroup(PGrandesRetiradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PGrandesRetiradasLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Banco5)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PGrandesRetiradasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19)
                        .addGap(7, 7, 7)))
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PGrandesRetiradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(2, 2, 2)
                .addGroup(PGrandesRetiradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PGrandesRetiradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(225, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("5", PGrandesRetiradas);

        PEditar.setBackground(new java.awt.Color(255, 255, 255));
        PEditar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar limites e taxas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        Banco6.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        Banco6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/banco.png"))); // NOI18N
        Banco6.setText("Banco Paradigmas");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Cadastra/Edita os limites de retiradas negativas e também da taxa de juros da poupança");

        jLabel24.setText("Número da conta:");

        jButton7.setText("Procurar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel26.setText("Limite de retiradas negativas:");

        jTextField17.setEnabled(false);

        jLabel27.setText("Taxa de juros da poupança: ");

        jTextField19.setEnabled(false);

        jButton8.setText("Aplicar");
        jButton8.setEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Aplicar");
        jButton9.setEnabled(false);

        javax.swing.GroupLayout PEditarLayout = new javax.swing.GroupLayout(PEditar);
        PEditar.setLayout(PEditarLayout);
        PEditarLayout.setHorizontalGroup(
            PEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator13)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PEditarLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(Banco6)
                .addGap(11, 11, 11))
            .addGroup(PEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator14)
                .addContainerGap())
            .addGroup(PEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PEditarLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jButton7))
                    .addGroup(PEditarLayout.createSequentialGroup()
                        .addGroup(PEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PEditarLayout.createSequentialGroup()
                                .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton9))
                            .addGroup(PEditarLayout.createSequentialGroup()
                                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton8)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PEditarLayout.setVerticalGroup(
            PEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PEditarLayout.createSequentialGroup()
                .addGroup(PEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PEditarLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Banco6)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PEditarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23)
                        .addGap(7, 7, 7)))
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addContainerGap(272, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("6", PEditar);

        PCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        PCadastrar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        Banco7.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        Banco7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/banco.png"))); // NOI18N
        Banco7.setText("Banco Paradigmas");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Insira os dados do usuário");

        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });

        jLabel28.setText("Nome:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Cliente", "Gerente" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel31.setText("Usuário:");

        jButton3.setText("Cadastrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jLabel32.setText("Senha:");

        javax.swing.GroupLayout PCadastrarLayout = new javax.swing.GroupLayout(PCadastrar);
        PCadastrar.setLayout(PCadastrarLayout);
        PCadastrarLayout.setHorizontalGroup(
            PCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator15)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PCadastrarLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 520, Short.MAX_VALUE)
                .addComponent(Banco7)
                .addGap(11, 11, 11))
            .addGroup(PCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel32))
                .addGap(10, 10, 10)
                .addGroup(PCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField18, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jPasswordField1))
                .addGap(30, 30, 30)
                .addGroup(PCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PCadastrarLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PCadastrarLayout.setVerticalGroup(
            PCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCadastrarLayout.createSequentialGroup()
                .addGroup(PCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PCadastrarLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Banco7)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PCadastrarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel25)
                        .addGap(7, 7, 7)))
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(PCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel32)))
                .addContainerGap(307, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("7", PCadastrar);

        PAlteraSenha.setBackground(new java.awt.Color(255, 255, 255));
        PAlteraSenha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alterar Senha", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        Banco8.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        Banco8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/banco.png"))); // NOI18N
        Banco8.setText("Banco Paradigmas");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("Digite a senha atual, e a senha desejada");

        jButton10.setText("Alterar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });

        jLabel35.setText("Senha Nova:");

        jLabel29.setText("Senha Atual:");

        jPasswordField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PAlteraSenhaLayout = new javax.swing.GroupLayout(PAlteraSenha);
        PAlteraSenha.setLayout(PAlteraSenhaLayout);
        PAlteraSenhaLayout.setHorizontalGroup(
            PAlteraSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAlteraSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator16)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PAlteraSenhaLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 436, Short.MAX_VALUE)
                .addComponent(Banco8)
                .addGap(11, 11, 11))
            .addGroup(PAlteraSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PAlteraSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton10)
                    .addGroup(PAlteraSenhaLayout.createSequentialGroup()
                        .addGroup(PAlteraSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PAlteraSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordField2, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(jPasswordField3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PAlteraSenhaLayout.setVerticalGroup(
            PAlteraSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAlteraSenhaLayout.createSequentialGroup()
                .addGroup(PAlteraSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PAlteraSenhaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Banco8)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PAlteraSenhaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel30)
                        .addGap(7, 7, 7)))
                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PAlteraSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(PAlteraSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addContainerGap(283, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("8", PAlteraSenha);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonVerificaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVerificaClienteActionPerformed
        this.jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_ButtonVerificaClienteActionPerformed

    private void ButtonVerificaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVerificaContaActionPerformed
        this.jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_ButtonVerificaContaActionPerformed

    private void ButtonAplicaSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAplicaSaldoActionPerformed
       this.jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_ButtonAplicaSaldoActionPerformed

    private void ButtonRetiradasGrandesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRetiradasGrandesActionPerformed
        this.jTabbedPane1.setSelectedIndex(6);
    }//GEN-LAST:event_ButtonRetiradasGrandesActionPerformed

    private void ButtonLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogout1ActionPerformed
        new MenuLogin(ListaUsuarios, false).setVisible(true);        
        setVisible(false);
        dispose();
    }//GEN-LAST:event_ButtonLogout1ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void ButtonLimitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLimitesActionPerformed
        this.jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_ButtonLimitesActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        verificaCadastro(jTextField18.getText(), new String(jPasswordField1.getPassword()), jComboBox2.getSelectedIndex());
        AtualizaBox();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed

    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void ButtonTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTransferenciaActionPerformed
        this.jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_ButtonTransferenciaActionPerformed

    private void ButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastroActionPerformed
        this.jTabbedPane1.setSelectedIndex(7);
    }//GEN-LAST:event_ButtonCadastroActionPerformed

    private void ButtonAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAlterarSenhaActionPerformed
        this.jTabbedPane1.setSelectedIndex(8);
    }//GEN-LAST:event_ButtonAlterarSenhaActionPerformed

    private void jPasswordField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VerificaInfoConta(Integer.parseInt(jTextField2.getText()));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VerificaClientes(jComboBox1.getSelectedIndex());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void PMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMenuMouseClicked

    }//GEN-LAST:event_PMenuMouseClicked

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        AtualizaBox();
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        if(jTextField4.getText().isEmpty())JOptionPane.showMessageDialog(null, "Número da conta inválido!");
        else if(jTextField8.getText().isEmpty() || Double.valueOf(jTextField8.getText()) < 0)JOptionPane.showMessageDialog(null, "Saldo invalido!");
        Aplica(Integer.valueOf(jTextField4.getText()), Double.valueOf(jTextField8.getText()));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        taxaContaE(Integer.valueOf(jTextField16.getText()), Double.valueOf(jTextField17.getText()));
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        SetaTaxas(Integer.valueOf(jTextField16.getText()));
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGerencia(ListaUsuarios, indexGerente).setVisible(true);
                
            }
        });
    }
    
    public boolean Transfere(int nroConta1, int nroConta2, double saldo){
        Cliente C1 = new Cliente();
        Cliente C2 = new Cliente();
        int i1, i2, j1, j2;
        if(nroConta1 == nroConta2){
            JOptionPane.showMessageDialog(null, "Insira contas diferentes!");
            return false;
        }
        else{
            for(i1=0; i1<GLogado.getClientes().size(); i1++){
                for(j1=0; j1<GLogado.getClientes().get(i1).getContas().size(); j1++){
                    if(GLogado.getClientes().get(i1).getContas().get(j1).getNumero() == nroConta1) 
                        break;
                }
            }
            for(int i=0; i<GLogado.getClientes().size(); i++){
                for(int j=0; j<GLogado.getClientes().get(i).getContas().size(); j++){
                    if(GLogado.getClientes().get(i).getContas().get(j).getNumero() == nroConta1) 
                        GLogado.getClientes().get(i).getContas().get(j);
                }
            }
            if(C1 != null && C2 != null){
                
            }           
        }
    }    
    public boolean SetaTaxas(int nroConta){
        for(int i=0; i<GLogado.getClientes().size(); i++)
        {
                for(int j=0; j<GLogado.getClientes().get(i).getContas().size(); j++)
                {
                    if(GLogado.getClientes().get(i).getContas().get(j).getNumero() == nroConta) 
                    {
                                       
                        if(GLogado.getClientes().get(i).getContas().get(j).getTipo().equals("Especial"))
                        {
                            jTextField17.setEnabled(true);
                            jButton8.setEnabled(true);
                            return true;
                        }
                        else if(GLogado.getClientes().get(i).getContas().get(j).getTipo().equals("Poupanca"))
                        {
                            jTextField18.setEnabled(true);
                            jButton9.setEnabled(true);
                            return true;
                        }
                        else 
                        {
                            JOptionPane.showMessageDialog(null, "Esta conta não possui taxas a serem setadas");
                            return false;
                        }
                    }
             }
        }
        return false;
    }
    
    public boolean taxaContaE(int nroConta, double limite){
        if(limite > 0){
            for(int i=0; i<GLogado.getClientes().size(); i++)
            {
                for(int j=0; j<GLogado.getClientes().get(i).getContas().size(); j++)
                {
                    if(GLogado.getClientes().get(i).getContas().get(j).getNumero() == nroConta) 
                }
        }
    }
    
    public boolean Aplica(int nroConta, double quantidade){           
        for(int i=0; i<GLogado.getClientes().size(); i++){
            for(int j=0; j<GLogado.getClientes().get(i).getContas().size(); j++){
                if(GLogado.getClientes().get(i).getContas().get(j).getNumero() == nroConta){
                    GLogado.getClientes().get(i).getContas().get(j).Aplica(quantidade);
                    JOptionPane.showMessageDialog(null, "Saldo aplicado!");
                    jTextField9.setText(String.valueOf("R$ " + GLogado.getClientes().get(i).getContas().get(j).getSaldo()));                    
                    return true;
                }                  
            }
        }
        JOptionPane.showMessageDialog(null, "Conta não encontrada!");
        return false;
    }
    
    public boolean verificaCadastro(String NomeInserido, String SenhaInserida, int TipoInserido){
        if(NomeInserido.isEmpty() && SenhaInserida.isEmpty())JOptionPane.showMessageDialog(null, "Campos vazios!");
        else if(NomeInserido.isEmpty())JOptionPane.showMessageDialog(null, "Nome não inserido");
        else if(SenhaInserida.isEmpty())JOptionPane.showMessageDialog(null, "Senha não inserida");
        else if(TipoInserido == 0)JOptionPane.showMessageDialog(null, "Escolha o tipo de conta");          
        else{
            try{          
                String Tipo;
                if(TipoInserido == 1){
                    Tipo = "Cliente";
                    GLogado.CadastraCliente(NomeInserido, SenhaInserida);
                }
                else {
                    Tipo = "Gerente";
                    ListaUsuarios.add(GLogado.CadastraGerente(NomeInserido, SenhaInserida));
                }
                
                FileWriter Arq = new FileWriter("D:\\Usuario\\Documents\\PUC-Campinas\\4 semestre\\Paradigmas B\\Projeto/contas.txt", true);
                PrintWriter EscreveContas = new PrintWriter(Arq);   
                EscreveContas.println(Tipo);
                EscreveContas.println(NomeInserido);
                EscreveContas.println(SenhaInserida);
                EscreveContas.flush();
                EscreveContas.close();
                JOptionPane.showMessageDialog(null, "Usuário cadastrado!");
                return true;
            }
            catch(IOException Ex){
               Ex.printStackTrace();          
            }
        }
        return false;
    }   
    
    public void AtualizaBox(){
        jComboBox1.removeAllItems();
        Cliente C = new Cliente();
        for(int i=0; i<GLogado.getClientes().size(); i++){
            C = GLogado.getClientes().get(i);
            jComboBox1.addItem(C.getNome());
        }
    }
    
    public void ImprimeContasCliente(int id){
        Cliente C = GLogado.getClientes().get(id);
        int i;
        for(i=0; i<C.getContas().size(); i++){
            jTextArea1.setText(jTextArea1.getText() + "Tipo: " + C.getContas().get(id).getTipo()
            + "\tNumero: " + C.getContas().get(id).getNumero());
        }
        
    }
    
    public boolean VerificaInfoConta(int CodConta){
        Cliente C = new Cliente();            
        jTextField3.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextArea2.setText("");
        jTextField7.setText("");  
        for(int i=0; i<GLogado.getClientes().size(); i++){
            C = GLogado.getClientes().get(i);
            
            
            for(int j=0; j<C.getContas().size(); j++){
                if(C.getContas().get(j).getNumero() == CodConta){
                    jTextField3.setText(C.getNome());
                    jTextField5.setText(String.valueOf("R$ " + C.getContas().get(i).getSaldo()));
                    jTextField6.setText(C.getContas().get(i).getTipo());
                    jTextArea2.setText(C.getContas().get(i).getExtrato());
                    jTextField7.setText(String.valueOf(C.getContas().get(i).getNumero()));
                    return true;
                }
            }           
        }
        JOptionPane.showMessageDialog(null, "Conta não encontrada!");   
        return false;
    }
    
    public void VerificaClientes(int id){
        Cliente C = new Cliente();
        for(int i=0; i<GLogado.getClientes().size(); i++){
            C = GLogado.getClientes().get(i);
            
            for(int j=0; j<C.getContas().size(); j++)
                jTextArea1.setText(jTextArea1.getText() + "Conta " + C.getContas().get(j).getTipo() + "\tNúmero: " + C.getContas().get(j).getNumero()+ "\n");           
        }
    }
    
    
    public void AlteraSenha(){
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Banco;
    private javax.swing.JLabel Banco1;
    private javax.swing.JLabel Banco2;
    private javax.swing.JLabel Banco3;
    private javax.swing.JLabel Banco4;
    private javax.swing.JLabel Banco5;
    private javax.swing.JLabel Banco6;
    private javax.swing.JLabel Banco7;
    private javax.swing.JLabel Banco8;
    private javax.swing.JButton ButtonAlterarSenha;
    private javax.swing.JButton ButtonAplicaSaldo;
    private javax.swing.JButton ButtonCadastro;
    private javax.swing.JButton ButtonLimites;
    private javax.swing.JButton ButtonLogout1;
    private javax.swing.JButton ButtonRetiradasGrandes;
    private javax.swing.JButton ButtonTransferencia;
    private javax.swing.JButton ButtonVerificaCliente;
    private javax.swing.JButton ButtonVerificaConta;
    private javax.swing.JLabel IconAplica;
    private javax.swing.JLabel IconCadastro;
    private javax.swing.JLabel IconCliente;
    private javax.swing.JLabel IconConta;
    private javax.swing.JLabel IconLimite;
    private javax.swing.JLabel IconRetiradasCaras;
    private javax.swing.JLabel IconSenha;
    private javax.swing.JLabel IconTransferencia;
    private javax.swing.JPanel PAlteraSenha;
    private javax.swing.JPanel PAplicarDinheiro;
    private javax.swing.JPanel PCadastrar;
    private javax.swing.JPanel PEditar;
    private javax.swing.JPanel PGrandesRetiradas;
    private javax.swing.JPanel PMenu;
    private javax.swing.JPanel PTransferencias;
    private javax.swing.JPanel PVerificarCliente;
    private javax.swing.JPanel PVerificarConta;
    private javax.swing.JLabel TextSelecione1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
