/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.contacteditor;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class MenuCliente extends javax.swing.JFrame {
    private static ArrayList<Gerente> ListaUsuarios;
    private static int indexGerente;
    private static int indexCliente;
    private static Cliente ClienteLogado;
    
    
    public MenuCliente(ArrayList<Gerente> Lista, int indexG, int indexC) {
        initComponents();         
        ListaUsuarios = Lista;
        indexGerente = indexG;
        indexCliente = indexC;
        ClienteLogado = Lista.get(indexGerente).getClientes().get(indexCliente);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PMenu = new javax.swing.JPanel();
        TextSelecione = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ButtonNovaConta = new javax.swing.JButton();
        ButtonAplicarDinheiro = new javax.swing.JButton();
        ButtonRetirarDinheiro = new javax.swing.JButton();
        ButtonVerificarSaldo = new javax.swing.JButton();
        ButtonVerificarExtrato = new javax.swing.JButton();
        ButtonAlterarSenha = new javax.swing.JButton();
        ButtonLogout = new javax.swing.JButton();
        IconNova = new javax.swing.JLabel();
        IconAplicar = new javax.swing.JLabel();
        IconRemover = new javax.swing.JLabel();
        IconSaldo = new javax.swing.JLabel();
        IconExtrato = new javax.swing.JLabel();
        IconSenha = new javax.swing.JLabel();
        Banco = new javax.swing.JLabel();
        PAbrirConta = new javax.swing.JPanel();
        TextSelecione1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Banco1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PAplicar = new javax.swing.JPanel();
        TextSelecione2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Banco2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        PRetirar = new javax.swing.JPanel();
        TextSelecione3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        Banco3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        PVerificarSaldo = new javax.swing.JPanel();
        TextSelecione4 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        Banco4 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        PExtratos = new javax.swing.JPanel();
        TextSelecione5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        Banco5 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        PAlterarSenha = new javax.swing.JPanel();
        TextSelecione6 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        Banco6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton6 = new javax.swing.JButton();

        jScrollPane2.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PMenu.setBackground(new java.awt.Color(255, 255, 255));
        PMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        TextSelecione.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TextSelecione.setText("Selecione uma Opção");

        ButtonNovaConta.setText("Abrir conta");
        ButtonNovaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNovaContaActionPerformed(evt);
            }
        });

        ButtonAplicarDinheiro.setText("Aplicar dinheiro");
        ButtonAplicarDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAplicarDinheiroActionPerformed(evt);
            }
        });

        ButtonRetirarDinheiro.setText("Retirar dinheiro");
        ButtonRetirarDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRetirarDinheiroActionPerformed(evt);
            }
        });

        ButtonVerificarSaldo.setText("Verificar saldo");
        ButtonVerificarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVerificarSaldoActionPerformed(evt);
            }
        });

        ButtonVerificarExtrato.setText("Verificar extrato");
        ButtonVerificarExtrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVerificarExtratoActionPerformed(evt);
            }
        });

        ButtonAlterarSenha.setText("Alterar senha");
        ButtonAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAlterarSenhaActionPerformed(evt);
            }
        });

        ButtonLogout.setBackground(new java.awt.Color(255, 0, 51));
        ButtonLogout.setText("Logout");
        ButtonLogout.setName(""); // NOI18N
        ButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogoutActionPerformed(evt);
            }
        });

        IconNova.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/conta_nova.png"))); // NOI18N

        IconAplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dinheiro_add.png"))); // NOI18N

        IconRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dinheiro_rem.png"))); // NOI18N

        IconSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dinheiro.png"))); // NOI18N

        IconExtrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/extrato.png"))); // NOI18N

        IconSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/alterar_senha.png"))); // NOI18N

        Banco.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        Banco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/banco.png"))); // NOI18N
        Banco.setText("Banco Paradigmas");

        javax.swing.GroupLayout PMenuLayout = new javax.swing.GroupLayout(PMenu);
        PMenu.setLayout(PMenuLayout);
        PMenuLayout.setHorizontalGroup(
            PMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(PMenuLayout.createSequentialGroup()
                        .addGroup(PMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ButtonVerificarSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonAlterarSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonVerificarExtrato, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(ButtonNovaConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonAplicarDinheiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonRetirarDinheiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IconAplicar)
                            .addComponent(IconRemover)
                            .addComponent(IconExtrato)
                            .addComponent(IconSaldo)
                            .addComponent(IconNova)
                            .addComponent(IconSenha))
                        .addGap(299, 307, Short.MAX_VALUE)
                        .addComponent(ButtonLogout))
                    .addGroup(PMenuLayout.createSequentialGroup()
                        .addComponent(TextSelecione)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Banco)))
                .addContainerGap())
        );
        PMenuLayout.setVerticalGroup(
            PMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMenuLayout.createSequentialGroup()
                .addGroup(PMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PMenuLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(TextSelecione))
                    .addGroup(PMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Banco)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IconRemover, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PMenuLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonNovaConta)
                            .addComponent(IconNova, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonAplicarDinheiro)
                            .addComponent(IconAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonRetirarDinheiro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonVerificarSaldo)
                    .addComponent(IconSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonVerificarExtrato)
                    .addComponent(IconExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonLogout)
                    .addComponent(ButtonAlterarSenha)
                    .addComponent(IconSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Menu", PMenu);

        PAbrirConta.setBackground(new java.awt.Color(255, 255, 255));
        PAbrirConta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Abrir conta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        TextSelecione1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TextSelecione1.setText("Insira os dados");

        Banco1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        Banco1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/banco.png"))); // NOI18N
        Banco1.setText("Banco Paradigmas");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Conta Simples", "Conta Especial", "Conta Poupanca" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de conta:");

        jButton1.setText("Abrir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PAbrirContaLayout = new javax.swing.GroupLayout(PAbrirConta);
        PAbrirConta.setLayout(PAbrirContaLayout);
        PAbrirContaLayout.setHorizontalGroup(
            PAbrirContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAbrirContaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PAbrirContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(PAbrirContaLayout.createSequentialGroup()
                        .addComponent(TextSelecione1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                        .addComponent(Banco1))
                    .addGroup(PAbrirContaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PAbrirContaLayout.setVerticalGroup(
            PAbrirContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAbrirContaLayout.createSequentialGroup()
                .addGroup(PAbrirContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PAbrirContaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(TextSelecione1))
                    .addGroup(PAbrirContaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Banco1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PAbrirContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("1", PAbrirConta);

        PAplicar.setBackground(new java.awt.Color(255, 255, 255));
        PAplicar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aplicar Dinheiro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        TextSelecione2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TextSelecione2.setText("Aplicar dinheiro em uma de suas contas");

        Banco2.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        Banco2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/banco.png"))); // NOI18N
        Banco2.setText("Banco Paradigmas");

        jLabel2.setText("Conta:");

        jButton2.setText("Aplicar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Valor:");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PAplicarLayout = new javax.swing.GroupLayout(PAplicar);
        PAplicar.setLayout(PAplicarLayout);
        PAplicarLayout.setHorizontalGroup(
            PAplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAplicarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PAplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(PAplicarLayout.createSequentialGroup()
                        .addComponent(TextSelecione2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(Banco2))
                    .addGroup(PAplicarLayout.createSequentialGroup()
                        .addGroup(PAplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PAplicarLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PAplicarLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PAplicarLayout.setVerticalGroup(
            PAplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAplicarLayout.createSequentialGroup()
                .addGroup(PAplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PAplicarLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(TextSelecione2))
                    .addGroup(PAplicarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Banco2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PAplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PAplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("2", PAplicar);

        PRetirar.setBackground(new java.awt.Color(255, 255, 255));
        PRetirar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Retirar Dinheiro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        TextSelecione3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TextSelecione3.setText("Retirar dinheiro em uma de suas contas");

        Banco3.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        Banco3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/banco.png"))); // NOI18N
        Banco3.setText("Banco Paradigmas");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Conta Simples", "Conta Especial", "Conta Simples" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Conta:");

        jButton3.setText("Retirar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setText("Valor:");

        javax.swing.GroupLayout PRetirarLayout = new javax.swing.GroupLayout(PRetirar);
        PRetirar.setLayout(PRetirarLayout);
        PRetirarLayout.setHorizontalGroup(
            PRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PRetirarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addGroup(PRetirarLayout.createSequentialGroup()
                        .addComponent(TextSelecione3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addComponent(Banco3))
                    .addGroup(PRetirarLayout.createSequentialGroup()
                        .addGroup(PRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PRetirarLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PRetirarLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PRetirarLayout.setVerticalGroup(
            PRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PRetirarLayout.createSequentialGroup()
                .addGroup(PRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PRetirarLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(TextSelecione3))
                    .addGroup(PRetirarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Banco3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(7, 7, 7)
                .addGroup(PRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("3", PRetirar);

        PVerificarSaldo.setBackground(new java.awt.Color(255, 255, 255));
        PVerificarSaldo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Verificar Saldo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        TextSelecione4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TextSelecione4.setText("Verificar saldo em uma de suas contas");

        Banco4.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        Banco4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/banco.png"))); // NOI18N
        Banco4.setText("Banco Paradigmas");

        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo:");

        jButton4.setText("Verificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField3.setEnabled(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel9.setText("Saldo:");

        javax.swing.GroupLayout PVerificarSaldoLayout = new javax.swing.GroupLayout(PVerificarSaldo);
        PVerificarSaldo.setLayout(PVerificarSaldoLayout);
        PVerificarSaldoLayout.setHorizontalGroup(
            PVerificarSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PVerificarSaldoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PVerificarSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5)
                    .addGroup(PVerificarSaldoLayout.createSequentialGroup()
                        .addComponent(TextSelecione4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addComponent(Banco4))
                    .addGroup(PVerificarSaldoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PVerificarSaldoLayout.setVerticalGroup(
            PVerificarSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PVerificarSaldoLayout.createSequentialGroup()
                .addGroup(PVerificarSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PVerificarSaldoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(TextSelecione4))
                    .addGroup(PVerificarSaldoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Banco4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PVerificarSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PVerificarSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jButton4)
                        .addComponent(jLabel9))
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("4", PVerificarSaldo);

        PExtratos.setBackground(new java.awt.Color(255, 255, 255));
        PExtratos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ver Extratos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        TextSelecione5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TextSelecione5.setText("Ver extrato de uma de suas contas");

        Banco5.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        Banco5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/banco.png"))); // NOI18N
        Banco5.setText("Banco Paradigmas");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Conta Simples", "Conta Especial", "Conta Simples" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jButton5.setText("Verificar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel12.setText("Conta:");

        jLabel14.setText("Extrato:");

        javax.swing.GroupLayout PExtratosLayout = new javax.swing.GroupLayout(PExtratos);
        PExtratos.setLayout(PExtratosLayout);
        PExtratosLayout.setHorizontalGroup(
            PExtratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PExtratosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PExtratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6)
                    .addGroup(PExtratosLayout.createSequentialGroup()
                        .addComponent(TextSelecione5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Banco5))
                    .addGroup(PExtratosLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PExtratosLayout.setVerticalGroup(
            PExtratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PExtratosLayout.createSequentialGroup()
                .addGroup(PExtratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PExtratosLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(TextSelecione5))
                    .addGroup(PExtratosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Banco5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PExtratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PExtratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5)
                        .addComponent(jLabel12)
                        .addComponent(jLabel14))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("5", PExtratos);

        PAlterarSenha.setBackground(new java.awt.Color(255, 255, 255));
        PAlterarSenha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alterar Senha", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        TextSelecione6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TextSelecione6.setText("Ensira as senhas para altera-la");

        Banco6.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        Banco6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/banco.png"))); // NOI18N
        Banco6.setText("Banco Paradigmas");

        jLabel10.setText("Senha Atual:");

        jLabel11.setText("Senha Nova:");

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jButton6.setText("Alterar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PAlterarSenhaLayout = new javax.swing.GroupLayout(PAlterarSenha);
        PAlterarSenha.setLayout(PAlterarSenhaLayout);
        PAlterarSenhaLayout.setHorizontalGroup(
            PAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAlterarSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator7)
                    .addGroup(PAlterarSenhaLayout.createSequentialGroup()
                        .addComponent(TextSelecione6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                        .addComponent(Banco6))
                    .addGroup(PAlterarSenhaLayout.createSequentialGroup()
                        .addGroup(PAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton6)
                            .addGroup(PAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(PAlterarSenhaLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jPasswordField2))
                                .addGroup(PAlterarSenhaLayout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PAlterarSenhaLayout.setVerticalGroup(
            PAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAlterarSenhaLayout.createSequentialGroup()
                .addGroup(PAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PAlterarSenhaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(TextSelecione6))
                    .addGroup(PAlterarSenhaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Banco6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("6", PAlterarSenha);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonNovaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNovaContaActionPerformed
        this.jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_ButtonNovaContaActionPerformed

    private void ButtonAplicarDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAplicarDinheiroActionPerformed
        this.jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_ButtonAplicarDinheiroActionPerformed

    private void ButtonRetirarDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRetirarDinheiroActionPerformed
        this.jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_ButtonRetirarDinheiroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AbrirConta(jComboBox1.getSelectedIndex());
        AtualizaTodosBox();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ClienteLogado.getContas().get(jComboBox6.getSelectedIndex()).Aplica(Integer.valueOf(jTextField4.getText()));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(Integer.valueOf(jTextField2.getText()) > 110000)
            JOptionPane.showMessageDialog(null, "Apenas um gerente pode retirar quantias superiores a R$110.000,00");  
        else
            ClienteLogado.getContas().get(jComboBox3.getSelectedIndex()).Retira(Integer.valueOf(jTextField2.getText()));                    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTextField3.setText("R$ " + String.valueOf(ClienteLogado.getContas().get(jComboBox4.getSelectedIndex()).getSaldo()));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTextArea1.setText("");
        jTextArea1.setText(ClienteLogado.getContas().get(jComboBox5.getSelectedIndex()).getExtrato());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ButtonVerificarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVerificarSaldoActionPerformed
        this.jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_ButtonVerificarSaldoActionPerformed

    private void ButtonVerificarExtratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVerificarExtratoActionPerformed
        this.jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_ButtonVerificarExtratoActionPerformed

    private void ButtonAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAlterarSenhaActionPerformed
        this.jTabbedPane1.setSelectedIndex(6);
    }//GEN-LAST:event_ButtonAlterarSenhaActionPerformed

    private void ButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogoutActionPerformed
        new MenuLogin(ListaUsuarios, false).setVisible(true);
        setVisible(false);
        dispose();       
    }//GEN-LAST:event_ButtonLogoutActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed

    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        AlteraSenha(new String(jPasswordField1.getPassword()), new String(jPasswordField2.getPassword()));
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCliente(ListaUsuarios, indexGerente, indexCliente).setVisible(true);               
            }
        });
    }
    
    public void AbrirConta(int tipo){
        switch (tipo) {
            case 0:
                ClienteLogado.cadastraContaSimples(ClienteLogado.getNome());
                break;
            case 1:
                ClienteLogado.cadastraContaEspecial(ClienteLogado.getNome());
                break;
            default:
                ClienteLogado.cadastraContaPoupanca(ClienteLogado.getNome());
                break;
        }
        JOptionPane.showMessageDialog(null, "Conta criada com suceso!");  
    }
    
    public void AtualizaTodosBox(){
        AtualizaBox(jComboBox3);
        AtualizaBox(jComboBox4);
        AtualizaBox(jComboBox5);
        AtualizaBox(jComboBox6);
    }
    
    public void AtualizaBox(JComboBox Caixa){
        Caixa.removeAllItems();
        Conta C = new Conta();
        int auxS=1, auxE=1, auxP=1;
        for(int i=0; i<ClienteLogado.getContas().size();i++)
        {            
            C = ClienteLogado.getContas().get(i);
            if(C.getTipo().equals("Simples")){
                Caixa.addItem("ContaSimples " + auxS);
                auxS++;
            }
            else if(C.getTipo().equals("Especial")){
                Caixa.addItem("ContaEspecial " + auxE);
                auxE++;
            }
            else{
                Caixa.addItem("ContaPoupanca " + auxP);  
                auxP++;
            }
        }           
    }
    
    public boolean AlteraSenha(String SenhaAtual, String SenhaNova){
        if(SenhaAtual.isEmpty() || SenhaNova.isEmpty())JOptionPane.showMessageDialog(null, "Complete os dados corretamente!");  
        
        try {
            File ArquivoContas = new File("D:\\Usuario\\Documents\\PUC-Campinas\\4 semestre\\Paradigmas B\\Projeto/contas.txt");
            Scanner LeContas = new Scanner(ArquivoContas);
            while(LeContas.hasNextLine())
            {                             
                String TipoCadastrado = LeContas.nextLine();
                String NomeCadastrado = LeContas.nextLine();
                String SenhaCadastrada = LeContas.nextLine();
                LeContas.remove();
                
                if(NomeCadastrado.equals(ClienteLogado.getNome()) && SenhaAtual.equals(SenhaCadastrada))
                {
                    FileWriter Arq = new FileWriter("D:\\Usuario\\Documents\\PUC-Campinas\\4 semestre\\Paradigmas B\\Projeto/contas.txt", true);
                    PrintWriter EscreveContas = new PrintWriter(Arq);
                    EscreveContas.write(SenhaCadastrada.replace(SenhaCadastrada, SenhaNova));  
                    EscreveContas.printf(LeContas.locale(), SenhaNova);
                    EscreveContas.close();
                    JOptionPane.showMessageDialog(null, "Senha alterada com suceso!");  
                    return true;
                }                   
            } 
        }
        catch (IOException Ex) {
           Ex.printStackTrace();      
        }
        JOptionPane.showMessageDialog(null, "Senha incorreta!");
        return false;             
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Banco;
    private javax.swing.JLabel Banco1;
    private javax.swing.JLabel Banco2;
    private javax.swing.JLabel Banco3;
    private javax.swing.JLabel Banco4;
    private javax.swing.JLabel Banco5;
    private javax.swing.JLabel Banco6;
    private javax.swing.JButton ButtonAlterarSenha;
    private javax.swing.JButton ButtonAplicarDinheiro;
    private javax.swing.JButton ButtonLogout;
    private javax.swing.JButton ButtonNovaConta;
    private javax.swing.JButton ButtonRetirarDinheiro;
    private javax.swing.JButton ButtonVerificarExtrato;
    private javax.swing.JButton ButtonVerificarSaldo;
    private javax.swing.JLabel IconAplicar;
    private javax.swing.JLabel IconExtrato;
    private javax.swing.JLabel IconNova;
    private javax.swing.JLabel IconRemover;
    private javax.swing.JLabel IconSaldo;
    private javax.swing.JLabel IconSenha;
    private javax.swing.JPanel PAbrirConta;
    private javax.swing.JPanel PAlterarSenha;
    private javax.swing.JPanel PAplicar;
    private javax.swing.JPanel PExtratos;
    private javax.swing.JPanel PMenu;
    private javax.swing.JPanel PRetirar;
    private javax.swing.JPanel PVerificarSaldo;
    private javax.swing.JLabel TextSelecione;
    private javax.swing.JLabel TextSelecione1;
    private javax.swing.JLabel TextSelecione2;
    private javax.swing.JLabel TextSelecione3;
    private javax.swing.JLabel TextSelecione4;
    private javax.swing.JLabel TextSelecione5;
    private javax.swing.JLabel TextSelecione6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
